fs = require('fs')

const countries = {
  "en":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Åland Islands",
    "AL":"Albania",
    "AD":"Andorra",
    "AE":"United Arab Emirates",
    "AR":"Argentina",
    "AM":"Armenia",
    "AS":"American Samoa",
    "AQ":"Antarctica",
    "TF":"French Southern Territories",
    "AG":"Antigua and Barbuda",
    "AU":"Australia",
    "AT":"Austria",
    "AZ":"Azerbaijan",
    "BI":"Burundi",
    "BE":"Belgium",
    "BJ":"Benin",
    "BQ":"Bonaire, Sint Eustatius and Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgaria",
    "BH":"Bahrain",
    "BS":"Bahamas",
    "BA":"Bosnia and Herzegovina",
    "BL":"Saint Barthélemy",
    "BY":"Belarus",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivia",
    "BR":"Brazil",
    "BB":"Barbados",
    "BN":"Brunei Darussalam",
    "BT":"Bhutan",
    "BV":"Bouvet Island",
    "BW":"Botswana",
    "CF":"Central African Republic",
    "CA":"Canada",
    "CC":"Cocos (Keeling) Islands",
    "CH":"Switzerland",
    "CL":"Chile",
    "CN":"China",
    "CI":"Côte d'Ivoire",
    "CM":"Cameroon",
    "CD":"Congo, The Democratic Republic of the",
    "CG":"Congo",
    "CK":"Cook Islands",
    "CO":"Colombia",
    "KM":"Comoros",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curaçao",
    "CX":"Christmas Island",
    "KY":"Cayman Islands",
    "CY":"Cyprus",
    "CZ":"Czechia",
    "DE":"Germany",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DK":"Denmark",
    "DO":"Dominican Republic",
    "DZ":"Algeria",
    "EC":"Ecuador",
    "EG":"Egypt",
    "ER":"Eritrea",
    "EH":"Western Sahara",
    "ES":"Spain",
    "EE":"Estonia",
    "ET":"Ethiopia",
    "FI":"Finland",
    "FJ":"Fiji",
    "FK":"Falkland Islands (Malvinas)",
    "FR":"France",
    "FO":"Faroe Islands",
    "FM":"Micronesia, Federated States of",
    "GA":"Gabon",
    "GB":"United Kingdom",
    "GE":"Georgia",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinea",
    "GP":"Guadeloupe",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Equatorial Guinea",
    "GR":"Greece",
    "GD":"Grenada",
    "GL":"Greenland",
    "GT":"Guatemala",
    "GF":"French Guiana",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hong Kong",
    "HM":"Heard Island and McDonald Islands",
    "HN":"Honduras",
    "HR":"Croatia",
    "HT":"Haiti",
    "HU":"Hungary",
    "ID":"Indonesia",
    "IM":"Isle of Man",
    "IN":"India",
    "IO":"British Indian Ocean Territory",
    "IE":"Ireland",
    "IR":"Iran, Islamic Republic of",
    "IQ":"Iraq",
    "IS":"Iceland",
    "IL":"Israel",
    "IT":"Italy",
    "JM":"Jamaica",
    "JE":"Jersey",
    "JO":"Jordan",
    "JP":"Japan",
    "KZ":"Kazakhstan",
    "KE":"Kenya",
    "KG":"Kyrgyzstan",
    "KH":"Cambodia",
    "KI":"Kiribati",
    "KN":"Saint Kitts and Nevis",
    "KR":"Korea, Republic of",
    "KW":"Kuwait",
    "LA":"Lao People's Democratic Republic",
    "LB":"Lebanon",
    "LR":"Liberia",
    "LY":"Libya",
    "LC":"Saint Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Lithuania",
    "LU":"Luxembourg",
    "LV":"Latvia",
    "MO":"Macao",
    "MF":"Saint Martin (French part)",
    "MA":"Morocco",
    "MC":"Monaco",
    "MD":"Moldova",
    "MG":"Madagascar",
    "MV":"Maldives",
    "MX":"Mexico",
    "MH":"Marshall Islands",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongolia",
    "MP":"Northern Mariana Islands",
    "MZ":"Mozambique",
    "MR":"Mauritania",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Mauritius",
    "MW":"Malawi",
    "MY":"Malaysia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"New Caledonia",
    "NE":"Niger",
    "NF":"Norfolk Island",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Netherlands",
    "NO":"Norway",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"New Zealand",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Peru",
    "PH":"Philippines",
    "PW":"Palau",
    "PG":"Papua New Guinea",
    "PL":"Poland",
    "PR":"Puerto Rico",
    "KP":"Korea, Democratic People's Republic of",
    "PT":"Portugal",
    "PY":"Paraguay",
    "PS":"Palestine, State of",
    "PF":"French Polynesia",
    "QA":"Qatar",
    "RE":"Réunion",
    "RO":"Romania",
    "RU":"Russian Federation",
    "RW":"Rwanda",
    "SA":"Saudi Arabia",
    "SD":"Sudan",
    "SN":"Senegal",
    "SG":"Singapore",
    "GS":"South Georgia and the South Sandwich Islands",
    "SH":"Saint Helena, Ascension and Tristan da Cunha",
    "SJ":"Svalbard and Jan Mayen",
    "SB":"Solomon Islands",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"Saint Pierre and Miquelon",
    "RS":"Serbia",
    "SS":"South Sudan",
    "ST":"Sao Tome and Principe",
    "SR":"Suriname",
    "SK":"Slovakia",
    "SI":"Slovenia",
    "SE":"Sweden",
    "SZ":"Eswatini",
    "SX":"Sint Maarten (Dutch part)",
    "SC":"Seychelles",
    "SY":"Syrian Arab Republic",
    "TC":"Turks and Caicos Islands",
    "TD":"Chad",
    "TG":"Togo",
    "TH":"Thailand",
    "TJ":"Tajikistan",
    "TK":"Tokelau",
    "TM":"Turkmenistan",
    "TL":"Timor-Leste",
    "TO":"Tonga",
    "TT":"Trinidad and Tobago",
    "TN":"Tunisia",
    "TR":"Turkey",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ukraine",
    "UM":"United States Minor Outlying Islands",
    "UY":"Uruguay",
    "US":"United States",
    "UZ":"Uzbekistan",
    "VA":"Holy See (Vatican City State)",
    "VC":"Saint Vincent and the Grenadines",
    "VE":"Venezuela",
    "VG":"Virgin Islands, British",
    "VI":"Virgin Islands, U.S.",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis and Futuna",
    "WS":"Samoa",
    "YE":"Yemen",
    "ZA":"South Africa",
    "ZM":"Zambia",
    "ZW":"Zimbabwe"
  },
  "sv":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Åland",
    "AL":"Albanien",
    "AD":"Andorra",
    "AE":"Förenade Arabemiraten",
    "AR":"Argentina",
    "AM":"Armenien",
    "AS":"Amerikanska Samoa",
    "AQ":"Antarktis",
    "TF":"Franska sydterritorierna",
    "AG":"Antigua och Barbuda",
    "AU":"Australien",
    "AT":"Österrike",
    "AZ":"Azerbajdzjan",
    "BI":"Burundi",
    "BE":"Belgien",
    "BJ":"Benin",
    "BQ":"Bonaire, Sint Eustatius och Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgarien",
    "BH":"Bahrain",
    "BS":"Bahamas",
    "BA":"Bosnien-Hercegovina",
    "BL":"Saint-Barthélemy",
    "BY":"Vitryssland",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivia",
    "BR":"Brasilien",
    "BB":"Barbados",
    "BN":"Brunei",
    "BT":"Bhutan",
    "BV":"Bouvetön",
    "BW":"Botswana",
    "CF":"Centralafrikanska republiken",
    "CA":"Kanada",
    "CC":"Kokosöarna",
    "CH":"Schweiz",
    "CL":"Chile",
    "CN":"Kina",
    "CI":"Elfenbenskusten",
    "CM":"Kamerun",
    "CD":"Kongo, demokratiska republiken",
    "CG":"Kongo",
    "CK":"Cooköarna",
    "CO":"Colombia",
    "KM":"Comorerna",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Kuba",
    "CW":"Curaçao",
    "CX":"Julön",
    "KY":"Caymanöarna",
    "CY":"Cypern",
    "CZ":"Czechia",
    "DE":"Tyskland",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DK":"Danmark",
    "DO":"Dominikanska republiken",
    "DZ":"Algeriet",
    "EC":"Ecuador",
    "EG":"Egypten",
    "ER":"Eritrea",
    "EH":"Västsahara",
    "ES":"Spanien",
    "EE":"Estland",
    "ET":"Etiopien",
    "FI":"Finland",
    "FJ":"Fiji",
    "FK":"Falklandsöarna (Malvinas)",
    "FR":"Frankrike",
    "FO":"Färöarna",
    "FM":"Mikronesien, federala staterna",
    "GA":"Gabon",
    "GB":"Förenade kungariket",
    "GE":"Georgien",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinea",
    "GP":"Guadeloupe",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Ekvatorialguinea",
    "GR":"Grekland",
    "GD":"Grenada",
    "GL":"Grönland",
    "GT":"Guatemala",
    "GF":"Franska Guiana",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hong Kong",
    "HM":"Heardön och McDonaldöarna",
    "HN":"Honduras",
    "HR":"Kroatien",
    "HT":"Haiti",
    "HU":"Ungern",
    "ID":"Indonesien",
    "IM":"Isle of Man",
    "IN":"Indien",
    "IO":"Brittiskt territorium i Indiska Oceanen",
    "IE":"Irland",
    "IR":"Iran, islamiska republiken",
    "IQ":"Irak",
    "IS":"Island",
    "IL":"Israel",
    "IT":"Italien",
    "JM":"Jamaica",
    "JE":"Jersey",
    "JO":"Jordanien",
    "JP":"Japan",
    "KZ":"Kazakstan",
    "KE":"Kenya",
    "KG":"Kirgisistan",
    "KH":"Kambodja",
    "KI":"Kiribati",
    "KN":"Sankt Kitts och Nevis",
    "KR":"Sydkorea",
    "KW":"Kuwait",
    "LA":"Demokratiska folkrepubliken Lao",
    "LB":"Libanon",
    "LR":"Liberia",
    "LY":"Libyen",
    "LC":"Sankt Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Litauen",
    "LU":"Luxemburg",
    "LV":"Lettland",
    "MO":"Macao",
    "MF":"Saint Martin (franska delen)",
    "MA":"Marocko",
    "MC":"Monaco",
    "MD":"Moldavien",
    "MG":"Madagaskar",
    "MV":"Maldiverna",
    "MX":"Mexico",
    "MH":"Marshallöarna",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongoliet",
    "MP":"Nordmarianerna",
    "MZ":"Moçambique",
    "MR":"Mauretanien",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Mauritius",
    "MW":"Malawi",
    "MY":"Malaysia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"Nya Kaledonien",
    "NE":"Niger",
    "NF":"Norfolköarna",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Nederländerna",
    "NO":"Norge",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"Nya Zeeland",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Peru",
    "PH":"Filippinerna",
    "PW":"Palau",
    "PG":"Papua Nya Guinea",
    "PL":"Polen",
    "PR":"Puerto Rico",
    "KP":"Korea, demokratiska folkrepubliken",
    "PT":"Portugal",
    "PY":"Paraguay",
    "PS":"Staten Palestina",
    "PF":"Franska Polynesien",
    "QA":"Qatar",
    "RE":"Réunion",
    "RO":"Rumänien",
    "RU":"Ryska federationen",
    "RW":"Rwanda",
    "SA":"Saudiarabien",
    "SD":"Sudan",
    "SN":"Senegal",
    "SG":"Singapore",
    "GS":"Sydgeorgien och södra Sandwichöarna",
    "SH":"Saint Helena, Ascension och Tristan da Cunha",
    "SJ":"Svalbard och Jan Mayen",
    "SB":"Salomonöarna",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"Sankt Pierre och Miquelon",
    "RS":"Serbien",
    "SS":"Sydsudan",
    "ST":"São Tomé och Príncipe",
    "SR":"Surinam",
    "SK":"Slovakien",
    "SI":"Slovenien",
    "SE":"Sverige",
    "SZ":"Eswatini",
    "SX":"Sint Maarten (nederländska delen)",
    "SC":"Seychellerna",
    "SY":"Syriska arabrepubliken",
    "TC":"Turks- och Caicosöarna",
    "TD":"Tchad",
    "TG":"Togo",
    "TH":"Thailand",
    "TJ":"Tadzjikistan",
    "TK":"Tokelau",
    "TM":"Turkmenistan",
    "TL":"Östtimor",
    "TO":"Tonga",
    "TT":"Trinidad och Tobago",
    "TN":"Tunisien",
    "TR":"Turkiet",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ukraina",
    "UM":"USA:s avlägsna mindre öar",
    "UY":"Uruguay",
    "US":"USA",
    "UZ":"Uzbekistan",
    "VA":"Vatikanstaten",
    "VC":"Sankt Vincent och Grenadinerna",
    "VE":"Venezuela",
    "VG":"Jungfruöarna, brittiska",
    "VI":"Jungfruöarna, amerikanska",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis och Futuna",
    "WS":"Samoa",
    "YE":"Yemen",
    "ZA":"Sydafrika",
    "ZM":"Zambia",
    "ZW":"Zimbabwe"
  },
  "da":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Åland",
    "AL":"Albanien",
    "AD":"Andorra",
    "AE":"Forenede Arabiske Emirater",
    "AR":"Argentina",
    "AM":"Armenien",
    "AS":"Amerikansk Samoa",
    "AQ":"Antarktis",
    "TF":"Sydlige Franske Territorier",
    "AG":"Antigua og Barbuda",
    "AU":"Australien",
    "AT":"Østrig",
    "AZ":"Aserbajdsjan",
    "BI":"Burundi",
    "BE":"Belgien",
    "BJ":"Benin",
    "BQ":"Bonaire, Sint Eustatius og Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgarien",
    "BH":"Bahrain",
    "BS":"Bahamas",
    "BA":"Bosnien-Herzegovina",
    "BL":"Sankt Bartolomæus",
    "BY":"Hviderusland",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivia",
    "BR":"Brasilien",
    "BB":"Barbados",
    "BN":"Brunei",
    "BT":"Bhutan",
    "BV":"Bouvet-øen",
    "BW":"Botswana",
    "CF":"Centralafrikanske Republik",
    "CA":"Canada",
    "CC":"Cocosøerne (Keelingøerne)",
    "CH":"Schweiz",
    "CL":"Chile",
    "CN":"Kina",
    "CI":"Elfenbenskysten",
    "CM":"Cameroun",
    "CD":"Den Demokratiske Republik Congo",
    "CG":"Congo",
    "CK":"Cookøerne",
    "CO":"Columbia",
    "KM":"Comorerne",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curaçao",
    "CX":"Juleøen",
    "KY":"Caymanøerne",
    "CY":"Cypern",
    "CZ":"Czechia",
    "DE":"Tyskland",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DK":"Danmark",
    "DO":"Dominikanske Republik",
    "DZ":"Algeriet",
    "EC":"Ecuador",
    "EG":"Egypten",
    "ER":"Eritrea",
    "EH":"Vestsahara",
    "ES":"Spanien",
    "EE":"Estland",
    "ET":"Etiopien",
    "FI":"Finland",
    "FJ":"Fiji",
    "FK":"Falklandsøerne (Malvinas)",
    "FR":"Frankrig",
    "FO":"Færøerne",
    "FM":"Mikronesiens Forenede Stater",
    "GA":"Gabon",
    "GB":"Storbritannien",
    "GE":"Georgien",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinea",
    "GP":"Guadeloupe",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Ækvatorialguinea",
    "GR":"Grækenland",
    "GD":"Grenada",
    "GL":"Grønland",
    "GT":"Guatemala",
    "GF":"Fransk Guinea",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hong Kong",
    "HM":"Heard-øen og McDonald-øerne",
    "HN":"Honduras",
    "HR":"Kroatien",
    "HT":"Haiti",
    "HU":"Ungarn",
    "ID":"Indonesien",
    "IM":"Isle of Man",
    "IN":"Indien",
    "IO":"British Indian Ocean Territory",
    "IE":"Irland",
    "IR":"Iran, Den Islamiske Republik",
    "IQ":"Irak",
    "IS":"Island",
    "IL":"Israel",
    "IT":"Italien",
    "JM":"Jamaica",
    "JE":"Jersey",
    "JO":"Jordan",
    "JP":"Japan",
    "KZ":"Kasakhstan",
    "KE":"Kenya",
    "KG":"Kirgisistan",
    "KH":"Cambodja",
    "KI":"Kiribati",
    "KN":"Sankt Kitts og Nevis",
    "KR":"Korea, Republikken",
    "KW":"Kuwait",
    "LA":"Lao, Folkets Demokratiske Republik",
    "LB":"Libanon",
    "LR":"Liberia",
    "LY":"Libyen",
    "LC":"Sankt Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Litauen",
    "LU":"Luxemburg",
    "LV":"Letland",
    "MO":"Macao",
    "MF":"Sankt Martin (Fransk del)",
    "MA":"Marokko",
    "MC":"Monaco",
    "MD":"Moldova",
    "MG":"Madagaskar",
    "MV":"Maldiverne",
    "MX":"Mexico",
    "MH":"Marshalløerne",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Burma",
    "ME":"Montenegro",
    "MN":"Mongoliet",
    "MP":"Nordmarianerne",
    "MZ":"Mocambique",
    "MR":"Mauretanien",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Mauritius",
    "MW":"Malawi",
    "MY":"Malaysia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"Ny Kaledonien",
    "NE":"Niger",
    "NF":"Norfolk Øen",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Holland",
    "NO":"Norge",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"New Zealand",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Peru",
    "PH":"Filippinerne",
    "PW":"Palau",
    "PG":"Papua Ny Guinea",
    "PL":"Polen",
    "PR":"Puerto Rico",
    "KP":"Korea, Den Demokratiske Folkerepublik",
    "PT":"Portugal",
    "PY":"Paraguay",
    "PS":"Palæstina, staten",
    "PF":"Fransk Polynesien",
    "QA":"Qatar",
    "RE":"Réunion",
    "RO":"Rumænien",
    "RU":"Russiske føderation",
    "RW":"Rwanda",
    "SA":"Saudi-Arabien",
    "SD":"Sudan",
    "SN":"Senegal",
    "SG":"Singapore",
    "GS":"South Georgia og De Sydlige Sandwichøer",
    "SH":"Sankt Helena, Ascension og Tristan da Cunha",
    "SJ":"Svalbard og Jan Mayen",
    "SB":"Salomonøerne",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"Sankt Pierre og Miquelon",
    "RS":"Serbien",
    "SS":"Sydsudan",
    "ST":"São Tomé og Príncipe",
    "SR":"Surinam",
    "SK":"Slovakiet",
    "SI":"Slovenien",
    "SE":"Sverige",
    "SZ":"Eswatini",
    "SX":"Sint Maarten (hollandsk del)",
    "SC":"Seychellerne",
    "SY":"Syriske Arabiske Republik",
    "TC":"Turks- og Caicosøerne",
    "TD":"Tchad",
    "TG":"Togo",
    "TH":"Thailand",
    "TJ":"Tadsjikistan",
    "TK":"Tokelau",
    "TM":"Turkmenistan",
    "TL":"Timor-Leste",
    "TO":"Tonga",
    "TT":"Trinidad og Tobago",
    "TN":"Tunesien",
    "TR":"Tyrkiet",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ukraine",
    "UM":"Fjerne, mindre Amerikanske øer",
    "UY":"Uruguay",
    "US":"USA",
    "UZ":"Usbekistan",
    "VA":"Vatikanstaten",
    "VC":"Sankt Vincent og Grenadinerne",
    "VE":"Venezuela",
    "VG":"Britiske Jomfruøer, De",
    "VI":"Amerikanske Jomfruøer, De",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis og Futunaøerne",
    "WS":"Samoa",
    "YE":"Yemen",
    "ZA":"Sydafrika",
    "ZM":"Zambia",
    "ZW":"Zimbabwe"
  },
  "nb":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Åland",
    "AL":"Albania",
    "AD":"Andorra",
    "AE":"De forente arabiske emirater",
    "AR":"Argentina",
    "AM":"Armenia",
    "AS":"Amerikansk Samoa",
    "AQ":"Antarktika",
    "TF":"Franske sørlige territorier",
    "AG":"Antigua og Barbuda",
    "AU":"Australia",
    "AT":"Østerrike",
    "AZ":"Aserbajdsjan",
    "BI":"Burundi",
    "BE":"Belgia",
    "BJ":"Benin",
    "BQ":"Bonaire, Sint Eustatius og Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgaria",
    "BH":"Bahrain",
    "BS":"Bahamas",
    "BA":"Bosnia-Hercegovina",
    "BL":"Saint Barthélemy",
    "BY":"Hviterussland",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivia",
    "BR":"Brasil",
    "BB":"Barbados",
    "BN":"Brunei Darussalam",
    "BT":"Bhutan",
    "BV":"Bouvetøya",
    "BW":"Botswana",
    "CF":"Den sentralafrikanske republikk",
    "CA":"Canada",
    "CC":"Kokosøyene",
    "CH":"Sveits",
    "CL":"Chile",
    "CN":"Kina",
    "CI":"Elfenbenskysten",
    "CM":"Kamerun",
    "CD":"Kongo, Den demokratiske republikk",
    "CG":"Kongo",
    "CK":"Cookøyene",
    "CO":"Colombia",
    "KM":"Komorene",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curaçao",
    "CX":"Christmasøya",
    "KY":"Caymanøyene",
    "CY":"Kypros",
    "CZ":"Czechia",
    "DE":"Tyskland",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DK":"Danmark",
    "DO":"Den dominikanske republikk",
    "DZ":"Algerie",
    "EC":"Ecuador",
    "EG":"Egypt",
    "ER":"Eritrea",
    "EH":"Vest-Sahara",
    "ES":"Spania",
    "EE":"Estland",
    "ET":"Etiopia",
    "FI":"Finland",
    "FJ":"Fiji",
    "FK":"Falklandsøyene",
    "FR":"Frankrike",
    "FO":"Færøyene",
    "FM":"Mikronesia, Føderasjonen",
    "GA":"Gabon",
    "GB":"Storbritannia",
    "GE":"Georgia",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinea",
    "GP":"Guadeloupe",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Ekvatorial-Guinea",
    "GR":"Hellas",
    "GD":"Grenada",
    "GL":"Grønland",
    "GT":"Guatemala",
    "GF":"Fransk Guyana",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hongkong",
    "HM":"Heard- og McDonaldøyene",
    "HN":"Honduras",
    "HR":"Kroatia",
    "HT":"Haiti",
    "HU":"Ungarn",
    "ID":"Indonesia",
    "IM":"Man",
    "IN":"India",
    "IO":"Det britiske området i Indiahavet",
    "IE":"Irland",
    "IR":"Iran, Den islamske republikk",
    "IQ":"Irak",
    "IS":"Island",
    "IL":"Israel",
    "IT":"Italia",
    "JM":"Jamaica",
    "JE":"Jersey",
    "JO":"Jordan",
    "JP":"Japan",
    "KZ":"Kasakhstan",
    "KE":"Kenya",
    "KG":"Kirgisistan",
    "KH":"Kambodsja",
    "KI":"Kiribati",
    "KN":"Saint Kitts og Nevis",
    "KR":"Korea, Republikken",
    "KW":"Kuwait",
    "LA":"Den demokratiske folkerepublikk Laos",
    "LB":"Libanon",
    "LR":"Liberia",
    "LY":"Libya",
    "LC":"Saint Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Litauen",
    "LU":"Luxembourg",
    "LV":"Latvia",
    "MO":"Macao",
    "MF":"Saint Martin (fransk del)",
    "MA":"Marokko",
    "MC":"Monaco",
    "MD":"Moldova",
    "MG":"Madagaskar",
    "MV":"Maldivene",
    "MX":"Mexico",
    "MH":"Marshalløyene",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongolia",
    "MP":"Nord-Marianene",
    "MZ":"Mosambik",
    "MR":"Mauritania",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Mauritius",
    "MW":"Malawi",
    "MY":"Malaysia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"Ny-Caledonia",
    "NE":"Niger",
    "NF":"Norfolkøya",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Nederland",
    "NO":"Norge",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"New Zealand",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Peru",
    "PH":"Filippinene",
    "PW":"Palau",
    "PG":"Papua Ny-Guinea",
    "PL":"Polen",
    "PR":"Puerto Rico",
    "KP":"Korea, Den demokratiske folkerepublikk",
    "PT":"Portugual",
    "PY":"Paraguay",
    "PS":"Palestina, staten",
    "PF":"Fransk Polynesia",
    "QA":"Qatar",
    "RE":"Réunion",
    "RO":"Romania",
    "RU":"Den russiske føderasjon",
    "RW":"Rwanda",
    "SA":"Saudi-Arabia",
    "SD":"Sudan",
    "SN":"Senegal",
    "SG":"Singapore",
    "GS":"Sør-Georgia og de sørlige Sandwichøyene",
    "SH":"St. Helena, Ascension og Tristan da Cunha",
    "SJ":"Svalbard og Jan Mayen",
    "SB":"Salomonøyene",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"Saint-Pierre-et-Miquelon",
    "RS":"Serbia",
    "SS":"Sør-Sudan",
    "ST":"São Tomé og Príncipe",
    "SR":"Surinam",
    "SK":"Slovakia",
    "SI":"Slovenia",
    "SE":"Sverige",
    "SZ":"Eswatini",
    "SX":"Sint Maarten (nederlandsk del)",
    "SC":"Seychellene",
    "SY":"Den arabiske republikk Syria",
    "TC":"Turks- og Caicosøyene",
    "TD":"Tsjad",
    "TG":"Togo",
    "TH":"Thailand",
    "TJ":"Tadsjikistan",
    "TK":"Tokelau",
    "TM":"Turkmenistan",
    "TL":"Øst-Timor",
    "TO":"Tonga",
    "TT":"Trinidad og Tobago",
    "TN":"Tunisia",
    "TR":"Tyrkia",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ukraina",
    "UM":"Mindre utenforliggende øyer til USA",
    "UY":"Uruguay",
    "US":"De forente stater",
    "UZ":"Usbekistan",
    "VA":"Vatikanstaten",
    "VC":"Saint Vincent og Grenadinene",
    "VE":"Venezuela",
    "VG":"Jomfruøyene (Storbritannia)",
    "VI":"Jomfruøyene (USA)",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis og Futunaøyene",
    "WS":"Samoa",
    "YE":"Jemen",
    "ZA":"Sør-Afrika",
    "ZM":"Zambia",
    "ZW":"Zimbabwe"
  },
  "fi":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Ahvenanmaa",
    "AL":"Albania",
    "AD":"Andorra",
    "AE":"Yhdistyneet arabiemiirikunnat",
    "AR":"Argentiina",
    "AM":"Armenia",
    "AS":"Amerikan Samoa",
    "AQ":"Antarktis",
    "TF":"Ranskan eteläiset alueet",
    "AG":"Antigua ja Barbuda",
    "AU":"Australia",
    "AT":"Itävalta",
    "AZ":"Azerbaidžan",
    "BI":"Burundi",
    "BE":"Belgia",
    "BJ":"Benin",
    "BQ":"Bonaire, Sint Eustatius ja Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgaria",
    "BH":"Bahrain",
    "BS":"Bahama",
    "BA":"Bosnia-Hertsegovina",
    "BL":"Saint Barthélemy",
    "BY":"Valko-Venäjä",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivia",
    "BR":"Brasilia",
    "BB":"Barbados",
    "BN":"Brunei Darussalamin valtio",
    "BT":"Bhutan",
    "BV":"Bouvet'nsaari",
    "BW":"Botswana",
    "CF":"Keski-Afrikan tasavalta",
    "CA":"Kanada",
    "CC":"Kookossaaret",
    "CH":"Sveitsi",
    "CL":"Chile",
    "CN":"Kiina",
    "CI":"Norsunluurannikko",
    "CM":"Kamerun",
    "CD":"Kongon demokraattinen tasavalta",
    "CG":"Kongo",
    "CK":"Cookinsaaret",
    "CO":"Kolumbia",
    "KM":"Komorit",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Kuuba",
    "CW":"Curaçao",
    "CX":"Joulusaari",
    "KY":"Caymansaaret",
    "CY":"Kypros",
    "CZ":"Czechia",
    "DE":"Saksa",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DK":"Tanska",
    "DO":"Dominikaaninen tasavalta",
    "DZ":"Algeria",
    "EC":"Ecuador",
    "EG":"Egypti",
    "ER":"Eritrea",
    "EH":"Länsi-Sahara",
    "ES":"Espanja",
    "EE":"Viro",
    "ET":"Etiopia",
    "FI":"Suomi",
    "FJ":"Fidži",
    "FK":"Falklandinsaaret",
    "FR":"Ranska",
    "FO":"Färsaaret",
    "FM":"Mikronesian liittovaltio",
    "GA":"Gabon",
    "GB":"Yhdistynyt kuningaskunta",
    "GE":"Georgia",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinea",
    "GP":"Guadeloupe",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Päiväntasaajan Guinea",
    "GR":"Kreikka",
    "GD":"Grenada",
    "GL":"Grönlanti",
    "GT":"Guatemala",
    "GF":"Ranskan Guayana",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hong Kong",
    "HM":"Heard ja McDonaldinsaaret",
    "HN":"Honduras",
    "HR":"Kroatia",
    "HT":"Haiti",
    "HU":"Unkari",
    "ID":"Indonesia",
    "IM":"Mansaari",
    "IN":"Intia",
    "IO":"Brittiläinen Intian valtameren alue",
    "IE":"Irlanti",
    "IR":"Iranin islamilainen tasavalta",
    "IQ":"Irak",
    "IS":"Islanti",
    "IL":"Israel",
    "IT":"Italia",
    "JM":"Jamaika",
    "JE":"Jersey",
    "JO":"Jordania",
    "JP":"Japani",
    "KZ":"Kazakstan",
    "KE":"Kenia",
    "KG":"Kirgisia",
    "KH":"Kambodža",
    "KI":"Kiribati",
    "KN":"Saint Kitts ja Nevis",
    "KR":"Korean tasavalta",
    "KW":"Kuwait",
    "LA":"Laos",
    "LB":"Libanon",
    "LR":"Liberia",
    "LY":"Libya",
    "LC":"Saint Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Liettua",
    "LU":"Luxemburg",
    "LV":"Latvia",
    "MO":"Macao",
    "MF":"Saint-Martin (ranskalainen osa)",
    "MA":"Marokko",
    "MC":"Monaco",
    "MD":"Moldova",
    "MG":"Madagaskar",
    "MV":"Malediivit",
    "MX":"Meksiko",
    "MH":"Marshallinsaaret",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongolia",
    "MP":"Pohjois-Mariaanit",
    "MZ":"Mosambik",
    "MR":"Mauritania",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Mauritius",
    "MW":"Malawi",
    "MY":"Malesia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"Uusi-Kaledonia",
    "NE":"Niger",
    "NF":"Norfolkinsaari",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Alankomaat",
    "NO":"Norja",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"Uusi-Seelanti",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Peru",
    "PH":"Filippiinit",
    "PW":"Palau",
    "PG":"Papua-Uusi-Guinea",
    "PL":"Puola",
    "PR":"Puerto Rico",
    "KP":"Korean demokraattinen kansantasavalta",
    "PT":"Portugali",
    "PY":"Paraguay",
    "PS":"Palestine, State of",
    "PF":"Ranskan Polynesia",
    "QA":"Qatar",
    "RE":"Réunion",
    "RO":"Romania",
    "RU":"Venäjän federaatio",
    "RW":"Ruanda",
    "SA":"Saudi-Arabia",
    "SD":"Sudan",
    "SN":"Senegal",
    "SG":"Singapore",
    "GS":"Etelä-Georgia ja Eteläiset Sandwichinsaaret",
    "SH":"Saint Helena, Ascension ja Tristan da Cunha",
    "SJ":"Svalbard ja Jan Mayen",
    "SB":"Salomonsaaret",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"Saint-Pierre ja Miquelon",
    "RS":"Serbia",
    "SS":"Etelä-Sudan",
    "ST":"São Tomé ja Príncipe",
    "SR":"Suriname",
    "SK":"Slovakia",
    "SI":"Slovenia",
    "SE":"Ruotsi",
    "SZ":"Eswatini",
    "SX":"Sint Maarten (hollantilainen osa)",
    "SC":"Seychellit",
    "SY":"Syyrian arabitasavalta",
    "TC":"Turks- ja Caicossaaret",
    "TD":"Tšad",
    "TG":"Togo",
    "TH":"Thaimaa",
    "TJ":"Tadžikistan",
    "TK":"Tokelau",
    "TM":"Turkmenistan",
    "TL":"Itä-Timor",
    "TO":"Tonga",
    "TT":"Trinidad ja Tobago",
    "TN":"Tunisia",
    "TR":"Turkki",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ukraina",
    "UM":"Yhdysvaltain pienet erillissaaret",
    "UY":"Uruguay",
    "US":"Yhdysvallat",
    "UZ":"Uzbekistan",
    "VA":"Pyhä istuin (Vatikaanivaltio)",
    "VC":"Saint Vincent ja Grenadiinit",
    "VE":"Venezuela",
    "VG":"Neitsytsaaret, Brittiläiset",
    "VI":"Neitsytsaaret, Yhdysvaltain",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis ja Futuna",
    "WS":"Samoa",
    "YE":"Jemen",
    "ZA":"Etelä-Afrikka",
    "ZM":"Sambia",
    "ZW":"Zimbabwe"
  },
  "es":{
    "AW":"Aruba",
    "AF":"Afganistán",
    "AO":"Angola",
    "AI":"Anguila",
    "AX":"Islas Äland",
    "AL":"Albania",
    "AD":"Andorra",
    "AE":"Emiratos Árabes Unidos",
    "AR":"Argentina",
    "AM":"Armenia",
    "AS":"Samoa Americana",
    "AQ":"Antártida",
    "TF":"Territorios Franceses del Sur",
    "AG":"Antigua y Barbuda",
    "AU":"Australia",
    "AT":"Austria",
    "AZ":"Azerbayán",
    "BI":"Burundi",
    "BE":"Bélgica",
    "BJ":"Benín",
    "BQ":"Islas BES (Caribe Neerlandés)",
    "BF":"Burquina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgaria",
    "BH":"Bahrein",
    "BS":"Bahamas",
    "BA":"Bosnia y Herzegovina",
    "BL":"San Bartolomé",
    "BY":"Bielorrusia",
    "BZ":"Belice",
    "BM":"Islas Bermudas",
    "BO":"Bolivia",
    "BR":"Brasil",
    "BB":"Barbados",
    "BN":"Brunei Darussalam",
    "BT":"Bhután",
    "BV":"Isla Bouvet",
    "BW":"Botsuana",
    "CF":"República Centro-africana",
    "CA":"Canadá",
    "CC":"Islas Cocos (Keeling)",
    "CH":"Suiza",
    "CL":"Chile",
    "CN":"China",
    "CI":"Costa de Marfíl",
    "CM":"Camerún",
    "CD":"Congo, República Democrática del",
    "CG":"Congo",
    "CK":"Islas Cook",
    "CO":"Colombia",
    "KM":"Comores, Islas",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curasao",
    "CX":"Isla de Navidad",
    "KY":"Islas Caimán",
    "CY":"Chipre",
    "CZ":"Czechia",
    "DE":"Alemania",
    "DJ":"Yibuti",
    "DM":"Dominica",
    "DK":"Dinamarca",
    "DO":"República Dominicana",
    "DZ":"Algeria",
    "EC":"Ecuador",
    "EG":"Egipto",
    "ER":"Eritrea",
    "EH":"Sahara Occidental",
    "ES":"España",
    "EE":"Estonia",
    "ET":"Etiopía",
    "FI":"Finlandia",
    "FJ":"Fiyi",
    "FK":"Islas Falkland (Malvinas)",
    "FR":"Francia",
    "FO":"Islas Feroe",
    "FM":"Micronesia, Estados Federados de",
    "GA":"Gabón",
    "GB":"Reino Unido",
    "GE":"Georgia",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinea",
    "GP":"Guadalupe",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Guinea Ecuatorial",
    "GR":"Grecia",
    "GD":"Granada",
    "GL":"Groenlandia",
    "GT":"Guatemala",
    "GF":"Guayana Francesa",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hong Kong",
    "HM":"Islas Heard e Islas McDonald",
    "HN":"Honduras",
    "HR":"Croacia",
    "HT":"Haití",
    "HU":"Hungría",
    "ID":"Indonesia",
    "IM":"Isla de Man",
    "IN":"India",
    "IO":"Británico del Océano Índico, Territorio",
    "IE":"Irlanda",
    "IR":"Irán, República islámica de",
    "IQ":"Irak",
    "IS":"Islandia",
    "IL":"Israel",
    "IT":"Italia",
    "JM":"Jamaica",
    "JE":"Jersey",
    "JO":"Jordania",
    "JP":"Japón",
    "KZ":"Kazajistán",
    "KE":"Kenia",
    "KG":"Kirgizstán",
    "KH":"Camboya",
    "KI":"Kiribati",
    "KN":"San Cristobo y Nevis",
    "KR":"Corea, República de",
    "KW":"Kuwait",
    "LA":"República Democrática Popular de Lao",
    "LB":"Líbano",
    "LR":"Liberia",
    "LY":"Libia",
    "LC":"Santa Lucía",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesoto",
    "LT":"Lituania",
    "LU":"Luxemburgo",
    "LV":"Letonia",
    "MO":"Macao",
    "MF":"San Martín (zona francesa)",
    "MA":"Marruecos",
    "MC":"Mónaco",
    "MD":"Moldavia",
    "MG":"Madagascar",
    "MV":"Islas Maldivas",
    "MX":"México",
    "MH":"Islas Marshall",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Birmania",
    "ME":"Montenegro",
    "MN":"Mongolia",
    "MP":"Islas Marianas del Norte",
    "MZ":"Mozambique",
    "MR":"Mauritania",
    "MS":"Montserrat",
    "MQ":"Martinica",
    "MU":"Mauricio",
    "MW":"Malawi",
    "MY":"Malasia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"Nueva Caledonia",
    "NE":"Niger",
    "NF":"Isla Norfolk",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Países Bajos",
    "NO":"Noruega",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"Nueva Zelanda",
    "OM":"Omán",
    "PK":"Pakistán",
    "PA":"Panamá",
    "PN":"Pitcairn",
    "PE":"Perú",
    "PH":"Filipinas",
    "PW":"Palau",
    "PG":"Papúa Nueva Guinea",
    "PL":"Polonia",
    "PR":"Puerto Rico",
    "KP":"Corea, República Democrática Popular de",
    "PT":"Portugal",
    "PY":"Paraguay",
    "PS":"Palestina, Estado de",
    "PF":"Polinesia Francesa",
    "QA":"Qatar",
    "RE":"Reunión",
    "RO":"Rumanía",
    "RU":"Federación Rusa",
    "RW":"Ruanda",
    "SA":"Arabia Saudí",
    "SD":"Sudán",
    "SN":"Senegal",
    "SG":"Singapur",
    "GS":"Georgia del Sur e Islas Sandwitch del Sur",
    "SH":"Santa Elena, Ascensión y Tristán de Acuña",
    "SJ":"Svalbard y Jan Mayen",
    "SB":"Islas Salomón",
    "SL":"Sierra Leona",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"San Pedro y Miquelon",
    "RS":"Serbia",
    "SS":"Sudán del Sur",
    "ST":"Santo Tomé y Príncipe",
    "SR":"Surinám",
    "SK":"Eslovaquia",
    "SI":"Eslovenia",
    "SE":"Suecia",
    "SZ":"Eswatini",
    "SX":"Isla de San Martín (zona holandsea)",
    "SC":"Seychelles",
    "SY":"República árabe de Siria",
    "TC":"Turks y Caicos, Islas",
    "TD":"Chad",
    "TG":"Togo",
    "TH":"Tailandia",
    "TJ":"Tadjikistán",
    "TK":"Tokelau",
    "TM":"Turkmenistán",
    "TL":"Timor Oriental",
    "TO":"Tonga",
    "TT":"Trinidad y Tobago",
    "TN":"Tunez",
    "TR":"Turquía",
    "TV":"Tuvalu",
    "TW":"Taiwán",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ucrania",
    "UM":"Islas menores exteriores de Estados Unidos",
    "UY":"Uruguay",
    "US":"Estados Unidos",
    "UZ":"Uzbekistán",
    "VA":"Santa Sede (Ciudad Estado del Vaticano)",
    "VC":"San Vicente y las Granadinas",
    "VE":"Venezuela",
    "VG":"Islas Vírgenes, Británicas",
    "VI":"Islas Vírgenes, de EEUU",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis y Futuna",
    "WS":"Samoa",
    "YE":"Yemen",
    "ZA":"Suráfrica",
    "ZM":"Zambia",
    "ZW":"Zimbabue"
  },
  "fr":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Åland, Îles",
    "AL":"Albanie",
    "AD":"Andorre",
    "AE":"Émirats arabes unis",
    "AR":"Argentine",
    "AM":"Arménie",
    "AS":"Samoa américaines",
    "AQ":"Antarctique",
    "TF":"Terres australes françaises",
    "AG":"Antigua-et-Barbuda",
    "AU":"Australie",
    "AT":"Autriche",
    "AZ":"Azerbaïdjan",
    "BI":"Burundi",
    "BE":"Belgique",
    "BJ":"Bénin",
    "BQ":"Bonaire, Saint-Eustache et Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgarie",
    "BH":"Bahreïn",
    "BS":"Bahamas",
    "BA":"Bosnie-Herzégovine",
    "BL":"Saint-Barthélemy",
    "BY":"Bélarus",
    "BZ":"Belize",
    "BM":"Bermudes",
    "BO":"Bolivie",
    "BR":"Brésil",
    "BB":"Barbade",
    "BN":"Brunéi Darussalam",
    "BT":"Bhoutan",
    "BV":"Bouvet, Île",
    "BW":"Botswana",
    "CF":"Centrafricaine, République",
    "CA":"Canada",
    "CC":"Cocos (Keeling), Îles",
    "CH":"Suisse",
    "CL":"Chili",
    "CN":"Chine",
    "CI":"Côte d'Ivoire",
    "CM":"Cameroun",
    "CD":"République démocratique du Congo",
    "CG":"Congo",
    "CK":"Cook, Îles",
    "CO":"Colombie",
    "KM":"Comores",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curaçao",
    "CX":"Christmas, Île",
    "KY":"Caïman, Îles",
    "CY":"Chypre",
    "CZ":"Czechia",
    "DE":"Allemagne",
    "DJ":"Djibouti",
    "DM":"Dominique",
    "DK":"Danemark",
    "DO":"Dominicaine, République",
    "DZ":"Algérie",
    "EC":"Équateur",
    "EG":"Égypte",
    "ER":"Érythrée",
    "EH":"Sahara Occidental",
    "ES":"Espagne",
    "EE":"Estonie",
    "ET":"Éthiopie",
    "FI":"Finlande",
    "FJ":"Fidji",
    "FK":"Falkland, Îles (Malvinas)",
    "FR":"France",
    "FO":"Féroé, Îles",
    "FM":"Micronésie, États fédérés de",
    "GA":"Gabon",
    "GB":"Royaume-Uni",
    "GE":"Géorgie",
    "GG":"Guernesey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinée",
    "GP":"Guadeloupe",
    "GM":"Gambie",
    "GW":"Guinée-Bissau",
    "GQ":"Guinée Équatoriale",
    "GR":"Grèce",
    "GD":"Grenade",
    "GL":"Groënland",
    "GT":"Guatemala",
    "GF":"Guyane française",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hong-Kong",
    "HM":"Heard, Île et McDonald, Îles",
    "HN":"Honduras",
    "HR":"Croatie",
    "HT":"Haïti",
    "HU":"Hongrie",
    "ID":"Indonésie",
    "IM":"Île de Man",
    "IN":"Inde",
    "IO":"Océan Indien, Territoire britannique de l'",
    "IE":"Irlande",
    "IR":"Iran, République islamique d'",
    "IQ":"Irak",
    "IS":"Islande",
    "IL":"Israël",
    "IT":"Italie",
    "JM":"Jamaïque",
    "JE":"Jersey",
    "JO":"Jordanie",
    "JP":"Japon",
    "KZ":"Kazakhstan",
    "KE":"Kenya",
    "KG":"Kirghizistan",
    "KH":"Cambodge",
    "KI":"Kiribati",
    "KN":"Saint-Kitts-et-Nevis",
    "KR":"Corée, République de",
    "KW":"Koweït",
    "LA":"Lao, République démocratique populaire",
    "LB":"Liban",
    "LR":"Libéria",
    "LY":"Libye",
    "LC":"Sainte-Lucie",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Lituanie",
    "LU":"Luxembourg",
    "LV":"Lettonie",
    "MO":"Macau",
    "MF":"Saint-Martin (partie française)",
    "MA":"Maroc",
    "MC":"Monaco",
    "MD":"Moldavie",
    "MG":"Madagascar",
    "MV":"Maldives",
    "MX":"Mexique",
    "MH":"Îles Marshall",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malte",
    "MM":"Myanmar",
    "ME":"Monténégro",
    "MN":"Mongolie",
    "MP":"Mariannes du Nord, Îles",
    "MZ":"Mozambique",
    "MR":"Mauritanie",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Maurice",
    "MW":"Malawi",
    "MY":"Malaisie",
    "YT":"Mayotte",
    "NA":"Namibie",
    "NC":"Nouvelle-Calédonie",
    "NE":"Niger",
    "NF":"Norfolk, Île",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Nioue",
    "NL":"Pays-Bas",
    "NO":"Norvège",
    "NP":"Népal",
    "NR":"Nauru",
    "NZ":"Nouvelle-Zélande",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Pérou",
    "PH":"Philippines",
    "PW":"Palaos",
    "PG":"Papouasie-Nouvelle-Guinée",
    "PL":"Pologne",
    "PR":"Porto Rico",
    "KP":"Corée, République populaire démocratique de",
    "PT":"Portugal",
    "PY":"Paraguay",
    "PS":"Palestine, État de",
    "PF":"Polynésie française",
    "QA":"Qatar",
    "RE":"Réunion, Île de la",
    "RO":"Roumanie",
    "RU":"Russie, Fédération de",
    "RW":"Rwanda",
    "SA":"Arabie saoudite",
    "SD":"Soudan",
    "SN":"Sénégal",
    "SG":"Singapour",
    "GS":"Géorgie du Sud et les îles Sandwich du Sud",
    "SH":"Sainte-Hélène, Ascension et Tristan da Cunha",
    "SJ":"Svalbard et île Jan Mayen",
    "SB":"Salomon, Îles",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marin",
    "SO":"Somalie",
    "PM":"Saint-Pierre-et-Miquelon",
    "RS":"Serbie",
    "SS":"Soudan du Sud",
    "ST":"Sao Tomé-et-Principe",
    "SR":"Surinam",
    "SK":"Slovaquie",
    "SI":"Slovénie",
    "SE":"Suède",
    "SZ":"Eswatini",
    "SX":"Saint-Martin (partie néerlandaise)",
    "SC":"Seychelles",
    "SY":"Syrienne, République arabe",
    "TC":"Turks et Caïques, Îles",
    "TD":"Tchad",
    "TG":"Togo",
    "TH":"Thaïlande",
    "TJ":"Tadjikistan",
    "TK":"Tokelau",
    "TM":"Turkménistan",
    "TL":"Timor-Leste",
    "TO":"Tonga",
    "TT":"Trinité-et-Tobago",
    "TN":"Tunisie",
    "TR":"Turquie",
    "TV":"Tuvalu",
    "TW":"Taïwan",
    "TZ":"Tanzanie",
    "UG":"Ouganda",
    "UA":"Ukraine",
    "UM":"Îles mineures éloignées des États-Unis d'Amérique",
    "UY":"Uruguay",
    "US":"États-Unis",
    "UZ":"Ouzbékistan",
    "VA":"Saint-Siège (état de la cité du Vatican)",
    "VC":"Saint-Vincent-et-les Grenadines",
    "VE":"Vénézuela",
    "VG":"Îles Vierges britanniques",
    "VI":"Îles Vierges des États-Unis",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis et Futuna",
    "WS":"Samoa",
    "YE":"Yémen",
    "ZA":"Afrique du Sud",
    "ZM":"Zambie",
    "ZW":"Zimbabwe"
  },
  "de":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Åland-Inseln",
    "AL":"Albanien",
    "AD":"Andorra",
    "AE":"Vereinigte Arabische Emirate",
    "AR":"Argentinien",
    "AM":"Armenien",
    "AS":"Amerikanisch-Samoa",
    "AQ":"Antarktis",
    "TF":"Französische Süd- und Antarktisgebiete",
    "AG":"Antigua und Barbuda",
    "AU":"Australien",
    "AT":"Österreich",
    "AZ":"Aserbaidschan",
    "BI":"Burundi",
    "BE":"Belgien",
    "BJ":"Benin",
    "BQ":"Bonaire, Sint Eustatius und Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesch",
    "BG":"Bulgarien",
    "BH":"Bahrain",
    "BS":"Bahamas",
    "BA":"Bosnien und Herzegowina",
    "BL":"Saint-Barthélemy",
    "BY":"Weißrussland",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivien",
    "BR":"Brasilien",
    "BB":"Barbados",
    "BN":"Brunei Darussalam",
    "BT":"Bhutan",
    "BV":"Bouvet-Insel",
    "BW":"Botsuana",
    "CF":"Zentralafrikanische Republik",
    "CA":"Kanada",
    "CC":"Kokos-(Keeling-)Inseln",
    "CH":"Schweiz",
    "CL":"Chile",
    "CN":"China",
    "CI":"Côte d'Ivoire",
    "CM":"Kamerun",
    "CD":"Demokratische Republik Kongo",
    "CG":"Kongo",
    "CK":"Cookinseln",
    "CO":"Kolumbien",
    "KM":"Komoren",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Kuba",
    "CW":"Curaçao",
    "CX":"Weihnachtsinseln",
    "KY":"Cayman-Inseln",
    "CY":"Zypern",
    "CZ":"Czechia",
    "DE":"Deutschland",
    "DJ":"Dschibuti",
    "DM":"Dominica",
    "DK":"Dänemark",
    "DO":"Dominikanische Republik",
    "DZ":"Algerien",
    "EC":"Ecuador",
    "EG":"Ägypten",
    "ER":"Eritrea",
    "EH":"Westsahara",
    "ES":"Spanien",
    "EE":"Estland",
    "ET":"Äthiopien",
    "FI":"Finnland",
    "FJ":"Fidschi",
    "FK":"Falklandinseln (Malwinen)",
    "FR":"Frankreich",
    "FO":"Färöer-Inseln",
    "FM":"Mikronesien, Föderierte Staaten von",
    "GA":"Gabun",
    "GB":"Vereinigtes Königreich",
    "GE":"Georgien",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinea",
    "GP":"Guadeloupe",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Äquatorialguinea",
    "GR":"Griechenland",
    "GD":"Grenada",
    "GL":"Grönland",
    "GT":"Guatemala",
    "GF":"Französisch-Guyana",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hongkong",
    "HM":"Heard und McDonaldinseln",
    "HN":"Honduras",
    "HR":"Kroatien",
    "HT":"Haiti",
    "HU":"Ungarn",
    "ID":"Indonesien",
    "IM":"Insel Man",
    "IN":"Indien",
    "IO":"Britisches Territorium im Indischen Ozean",
    "IE":"Irland",
    "IR":"Iran, Islamische Republik",
    "IQ":"Irak",
    "IS":"Island",
    "IL":"Israel",
    "IT":"Italien",
    "JM":"Jamaika",
    "JE":"Jersey",
    "JO":"Jordanien",
    "JP":"Japan",
    "KZ":"Kasachstan",
    "KE":"Kenia",
    "KG":"Kirgisistan",
    "KH":"Kambodscha",
    "KI":"Kiribati",
    "KN":"St. Kitts und Nevis",
    "KR":"Korea, Republik",
    "KW":"Kuwait",
    "LA":"Laos, Demokratische Volksrepublik",
    "LB":"Libanon",
    "LR":"Liberia",
    "LY":"Libyen",
    "LC":"St. Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Litauen",
    "LU":"Luxemburg",
    "LV":"Lettland",
    "MO":"Macao",
    "MF":"Saint Martin (Französischer Teil)",
    "MA":"Marokko",
    "MC":"Monaco",
    "MD":"Moldau",
    "MG":"Madagaskar",
    "MV":"Malediven",
    "MX":"Mexiko",
    "MH":"Marshallinseln",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongolei",
    "MP":"Nördliche Mariana-Inseln",
    "MZ":"Mosambik",
    "MR":"Mauretanien",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Mauritius",
    "MW":"Malawi",
    "MY":"Malaysia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"Neukaledonien",
    "NE":"Niger",
    "NF":"Norfolkinsel",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Niederlande",
    "NO":"Norwegen",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"Neuseeland",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Peru",
    "PH":"Philippinen",
    "PW":"Palau",
    "PG":"Papua-Neuguinea",
    "PL":"Polen",
    "PR":"Puerto Rico",
    "KP":"Korea, Demokratische Volksrepublik",
    "PT":"Portugal",
    "PY":"Paraguay",
    "PS":"Palästina, Staat",
    "PF":"Französisch-Polynesien",
    "QA":"Katar",
    "RE":"Réunion",
    "RO":"Rumänien",
    "RU":"Russische Föderation",
    "RW":"Ruanda",
    "SA":"Saudi-Arabien",
    "SD":"Sudan",
    "SN":"Senegal",
    "SG":"Singapur",
    "GS":"South Georgia und die Südlichen Sandwichinseln",
    "SH":"St. Helena, Ascension und Tristan da Cunha",
    "SJ":"Svalbard und Jan Mayen",
    "SB":"Salomoninseln",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"St. Pierre und Miquelon",
    "RS":"Serbien",
    "SS":"Südsudan",
    "ST":"São Tomé und Príncipe",
    "SR":"Suriname",
    "SK":"Slowakei",
    "SI":"Slowenien",
    "SE":"Schweden",
    "SZ":"Eswatini",
    "SX":"Saint-Martin (Niederländischer Teil)",
    "SC":"Seychellen",
    "SY":"Syrien, Arabische Republik",
    "TC":"Turks- und Caicosinseln",
    "TD":"Tschad",
    "TG":"Togo",
    "TH":"Thailand",
    "TJ":"Tadschikistan",
    "TK":"Tokelau",
    "TM":"Turkmenistan",
    "TL":"Timor-Leste",
    "TO":"Tonga",
    "TT":"Trinidad und Tobago",
    "TN":"Tunesien",
    "TR":"Türkei",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tansania",
    "UG":"Uganda",
    "UA":"Ukraine",
    "UM":"United States Minor Outlying Islands",
    "UY":"Uruguay",
    "US":"Vereinigte Staaten",
    "UZ":"Usbekistan",
    "VA":"Heiliger Stuhl (Staat Vatikanstadt)",
    "VC":"St. Vincent und die Grenadinen",
    "VE":"Venezuela",
    "VG":"Britische Jungferninseln",
    "VI":"Amerikanische Jungferninseln",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis und Futuna",
    "WS":"Samoa",
    "YE":"Jemen",
    "ZA":"Südafrika",
    "ZM":"Sambia",
    "ZW":"Simbabwe"
  },
  "nl":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Ålandseilanden",
    "AL":"Albanië",
    "AD":"Andorra",
    "AE":"Verenigde Arabische Emiraten",
    "AR":"Argentinië",
    "AM":"Armenië",
    "AS":"Amerikaans-Samoa",
    "AQ":"Antarctica",
    "TF":"Franse Zuidelijke Gebieden",
    "AG":"Antigua en Barbuda",
    "AU":"Australië",
    "AT":"Oostenrijk",
    "AZ":"Azerbeidzjan",
    "BI":"Burundi",
    "BE":"België",
    "BJ":"Benin",
    "BQ":"Bonaire, Sint Eustatius en Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgarije",
    "BH":"Bahrein",
    "BS":"Bahama's",
    "BA":"Bosnië en Herzegovina",
    "BL":"Saint-Barthélemy",
    "BY":"Wit-Rusland",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivia",
    "BR":"Brazilië",
    "BB":"Barbados",
    "BN":"Brunei",
    "BT":"Bhutan",
    "BV":"Bouvet eiland",
    "BW":"Botswana",
    "CF":"Centraal-Afrikaanse Republiek",
    "CA":"Canada",
    "CC":"Cocoseilanden",
    "CH":"Zwitserland",
    "CL":"Chili",
    "CN":"China",
    "CI":"Ivoorkust",
    "CM":"Kameroen",
    "CD":"Congo, Democratische Republiek",
    "CG":"Congo",
    "CK":"Cookeilanden",
    "CO":"Colombia",
    "KM":"Comoren",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curaçao",
    "CX":"Christmaseiland",
    "KY":"Caymaneilanden",
    "CY":"Cyprus",
    "CZ":"Czechia",
    "DE":"Duitsland",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DK":"Denemarken",
    "DO":"Dominicaanse Republiek",
    "DZ":"Algerije",
    "EC":"Ecuador",
    "EG":"Egypte",
    "ER":"Eritrea",
    "EH":"Westelijke Sahara",
    "ES":"Spanje",
    "EE":"Estland",
    "ET":"Ethiopië",
    "FI":"Finland",
    "FJ":"Fiji",
    "FK":"Falklandeilanden",
    "FR":"Frankrijk",
    "FO":"Faeröer",
    "FM":"Micronesia",
    "GA":"Gabon",
    "GB":"Verenigd Koninkrijk",
    "GE":"Georgië",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibraltar",
    "GN":"Guinee",
    "GP":"Guadeloupe",
    "GM":"Gambia",
    "GW":"Guinee-Bissau",
    "GQ":"Equatoriaal-Guinea",
    "GR":"Griekenland",
    "GD":"Grenada",
    "GL":"Groenland",
    "GT":"Guatemala",
    "GF":"Frans-Guyana",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hongkong",
    "HM":"Heardeiland en McDonaldeilanden",
    "HN":"Honduras",
    "HR":"Kroatië",
    "HT":"Haïti",
    "HU":"Hongarije",
    "ID":"Indonesië",
    "IM":"Eiland Man",
    "IN":"India",
    "IO":"Brits Territorium in de Indische Oceaan",
    "IE":"Ierland",
    "IR":"Iran",
    "IQ":"Irak",
    "IS":"IJsland",
    "IL":"Israël",
    "IT":"Italië",
    "JM":"Jamaica",
    "JE":"Jersey",
    "JO":"Jordanië",
    "JP":"Japan",
    "KZ":"Kazachstan",
    "KE":"Kenia",
    "KG":"Kirgizië",
    "KH":"Cambodja",
    "KI":"Kiribati",
    "KN":"Saint Kitts en Nevis",
    "KR":"Zuid-Korea",
    "KW":"Koeweit",
    "LA":"Laos Democratische Volksrepubliek",
    "LB":"Libanon",
    "LR":"Liberia",
    "LY":"Libië",
    "LC":"Saint Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Litouwen",
    "LU":"Luxemburg",
    "LV":"Letland",
    "MO":"Macau",
    "MF":"Sint-Maarten",
    "MA":"Marokko",
    "MC":"Monaco",
    "MD":"Moldavië",
    "MG":"Madagaskar",
    "MV":"Maldiven",
    "MX":"Mexico",
    "MH":"Marshalleilanden",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongolië",
    "MP":"Noordelijke Marianen",
    "MZ":"Mozambique",
    "MR":"Mauritanië",
    "MS":"Montserrat",
    "MQ":"Martinique",
    "MU":"Mauritius",
    "MW":"Malawi",
    "MY":"Maleisië",
    "YT":"Mayotte",
    "NA":"Namibië",
    "NC":"Nieuw-Caledonië",
    "NE":"Niger",
    "NF":"Norfolk",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Nederland",
    "NO":"Noorwegen",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"Nieuw-Zeeland",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairneilanden",
    "PE":"Peru",
    "PH":"Filipijnen",
    "PW":"Palau",
    "PG":"Papoea-Nieuw-Guinea",
    "PL":"Polen",
    "PR":"Puerto Rico",
    "KP":"Noord-Korea",
    "PT":"Portugal",
    "PY":"Paraguay",
    "PS":"Palestina",
    "PF":"Frans-Polynesië",
    "QA":"Qatar",
    "RE":"Réunion",
    "RO":"Roemenië",
    "RU":"Rusland",
    "RW":"Rwanda",
    "SA":"Saoedi-Arabië",
    "SD":"Soedan",
    "SN":"Senegal",
    "SG":"Singapore",
    "GS":"Zuid-Georgië en de Zuidelijke Sandwicheilanden",
    "SH":"Sint-Helena, Ascension en Tristan da Cunha",
    "SJ":"Spitsbergen en Jan Mayen",
    "SB":"Salomonseilanden",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalië",
    "PM":"Saint-Pierre en Miquelon",
    "RS":"Servië",
    "SS":"Zuid-Soedan",
    "ST":"Sao Tomé en Principe",
    "SR":"Suriname",
    "SK":"Slowakije, Slovakije",
    "SI":"Slovenië",
    "SE":"Zweden",
    "SZ":"Eswatini",
    "SX":"Sint Maarten (Nederlands deel)",
    "SC":"Seychellen",
    "SY":"Syrië",
    "TC":"Turks- en Caicoseilanden",
    "TD":"Tsjaad",
    "TG":"Togo",
    "TH":"Thailand",
    "TJ":"Tadzjikistan",
    "TK":"Tokelau-eilanden",
    "TM":"Turkmenistan",
    "TL":"Oost-Timor",
    "TO":"Tonga",
    "TT":"Trinidad en Tobago",
    "TN":"Tunesië",
    "TR":"Turkije",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Oeganda",
    "UA":"Oekraïne",
    "UM":"Kleine Pacifische eilanden van de Verenigde Staten",
    "UY":"Uruguay",
    "US":"Verenigde Staten",
    "UZ":"Oezbekistan",
    "VA":"Vaticaanstad",
    "VC":"Saint Vincent en de Grenadines",
    "VE":"Venezuela",
    "VG":"Maagdeneilanden, Britse",
    "VI":"Amerikaanse Maagdeneilanden",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis en Futuna",
    "WS":"Samoa",
    "YE":"Jemen",
    "ZA":"Zuid-Afrika",
    "ZM":"Zambia",
    "ZW":"Zimbabwe"
  },
  "it":{
    "AW":"Aruba",
    "AF":"Afghanistan",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Isole Åland",
    "AL":"Albania",
    "AD":"Andorra",
    "AE":"Emirati arabi uniti",
    "AR":"Argentina",
    "AM":"Armenia",
    "AS":"Samoa americane",
    "AQ":"Antartide",
    "TF":"Territori meridionali francesi",
    "AG":"Antigua e Barbuda",
    "AU":"Australia",
    "AT":"Austria",
    "AZ":"Azerbaigian",
    "BI":"Burundi",
    "BE":"Belgio",
    "BJ":"Benin",
    "BQ":"Bonaire, Saint Eustatius e Saba",
    "BF":"Burkina-Faso",
    "BD":"Bangladesh",
    "BG":"Bulgaria",
    "BH":"Bahrein",
    "BS":"Bahamas",
    "BA":"Bosnia-Erzegovina",
    "BL":"Saint-Barths",
    "BY":"Bielorussia",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolivia",
    "BR":"Brasile",
    "BB":"Barbados",
    "BN":"Brunei",
    "BT":"Bhutan",
    "BV":"Isola di Bouvet",
    "BW":"Botswana",
    "CF":"Repubblica Centrafricana",
    "CA":"Canada",
    "CC":"Isole Cocos (Keeling)",
    "CH":"Svizzera",
    "CL":"Cile",
    "CN":"Cina",
    "CI":"Costa d'Avorio",
    "CM":"Camerun",
    "CD":"Repubblica democratica del Congo",
    "CG":"Congo",
    "CK":"Isole Cook",
    "CO":"Colombia",
    "KM":"Comore",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curaçao",
    "CX":"Isola Christmas",
    "KY":"Isole Cayman",
    "CY":"Cipro",
    "CZ":"Czechia",
    "DE":"Germania",
    "DJ":"Gibuti",
    "DM":"Dominica",
    "DK":"Danimarca",
    "DO":"Repubblica Dominicana",
    "DZ":"Algeria",
    "EC":"Ecuador",
    "EG":"Egitto",
    "ER":"Eritrea",
    "EH":"Sahara occidentale",
    "ES":"Spagna",
    "EE":"Estonia",
    "ET":"Etiopia",
    "FI":"Finlandia",
    "FJ":"Fiji",
    "FK":"Isole Falkland (Malvine)",
    "FR":"Francia",
    "FO":"Isole Fær Øer",
    "FM":"Micronesia",
    "GA":"Gabon",
    "GB":"Regno Unito",
    "GE":"Georgia",
    "GG":"Guernsey",
    "GH":"Ghana",
    "GI":"Gibilterra",
    "GN":"Guinea",
    "GP":"Guadalupa",
    "GM":"Gambia",
    "GW":"Guinea-Bissau",
    "GQ":"Guinea equatoriale",
    "GR":"Grecia",
    "GD":"Grenada",
    "GL":"Groenlandia",
    "GT":"Guatemala",
    "GF":"Guyana francese",
    "GU":"Guam",
    "GY":"Guyana",
    "HK":"Hong Kong",
    "HM":"Isole Heard e McDonald",
    "HN":"Honduras",
    "HR":"Croazia",
    "HT":"Haiti",
    "HU":"Ungheria",
    "ID":"Indonesia",
    "IM":"Isola di Man",
    "IN":"India",
    "IO":"Territorio britannico dell'Oceano Indiano",
    "IE":"Irlanda",
    "IR":"Iran",
    "IQ":"Iraq",
    "IS":"Islanda",
    "IL":"Israele",
    "IT":"Italia",
    "JM":"Giamaica",
    "JE":"Jersey",
    "JO":"Giordania",
    "JP":"Giappone",
    "KZ":"Kazakistan",
    "KE":"Kenya",
    "KG":"Kirghizistan",
    "KH":"Cambogia",
    "KI":"Kiribati",
    "KN":"Saint Kitts e Nevis",
    "KR":"Corea del Sud",
    "KW":"Kuwait",
    "LA":"Laos",
    "LB":"Libano",
    "LR":"Liberia",
    "LY":"Libia",
    "LC":"Saint Lucia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesotho",
    "LT":"Lituania",
    "LU":"Lussemburgo",
    "LV":"Lettonia",
    "MO":"Macao",
    "MF":"Saint-Martin (Francia)",
    "MA":"Marocco",
    "MC":"Monaco",
    "MD":"Moldavia",
    "MG":"Madagascar",
    "MV":"Maldive",
    "MX":"Messico",
    "MH":"Isole Marshall",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongolia",
    "MP":"Marianne settentrionali",
    "MZ":"Mozambico",
    "MR":"Mauritania",
    "MS":"Montserrat",
    "MQ":"Martinica",
    "MU":"Maurizio",
    "MW":"Malawi",
    "MY":"Malaysia",
    "YT":"Mayotte",
    "NA":"Namibia",
    "NC":"Nuova Caledonia",
    "NE":"Niger",
    "NF":"Isola Norfolk",
    "NG":"Nigeria",
    "NI":"Nicaragua",
    "NU":"Niue",
    "NL":"Paesi Bassi",
    "NO":"Norvegia",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"Nuova Zelanda",
    "OM":"Oman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitcairn",
    "PE":"Perù",
    "PH":"Filippine",
    "PW":"Palau",
    "PG":"Papua Nuova Guinea",
    "PL":"Polonia",
    "PR":"Puerto Rico",
    "KP":"Corea del Nord",
    "PT":"Portogallo",
    "PY":"Paraguay",
    "PS":"Palestina, Stato di",
    "PF":"Polinesia francese",
    "QA":"Qatar",
    "RE":"Riunione",
    "RO":"Romania",
    "RU":"Russia",
    "RW":"Ruanda",
    "SA":"Arabia Saudita",
    "SD":"Sudan",
    "SN":"Senegal",
    "SG":"Singapore",
    "GS":"Georgia del Sud e Sandwich australi",
    "SH":"Saint Helena, Ascension e Tristan da Cunha",
    "SJ":"Svalbard e Jan Mayen",
    "SB":"Isole Salomone",
    "SL":"Sierra Leone",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somalia",
    "PM":"Saint-Pierre e Miquelon",
    "RS":"Serbia",
    "SS":"Sudan meridionale",
    "ST":"São Tomé e Príncipe",
    "SR":"Suriname",
    "SK":"Slovacchia",
    "SI":"Slovenia",
    "SE":"Svezia",
    "SZ":"Eswatini",
    "SX":"Sint Maarten (parte olandese)",
    "SC":"Seicelle",
    "SY":"Siria",
    "TC":"Isole Turks e Caicos",
    "TD":"Ciad",
    "TG":"Togo",
    "TH":"Thailandia",
    "TJ":"Tagikistan",
    "TK":"Tokelau",
    "TM":"Turkmenistan",
    "TL":"Timor orientale",
    "TO":"Tonga",
    "TT":"Trinidad e Tobago",
    "TN":"Tunisia",
    "TR":"Turchia",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ucraina",
    "UM":"Isole minori statunitensi",
    "UY":"Uruguay",
    "US":"Stati Uniti",
    "UZ":"Uzbekistan",
    "VA":"Santa Sede (Stato della Città del Vaticano)",
    "VC":"Saint Vincent e Grenadine",
    "VE":"Venezuela",
    "VG":"Isole Vergini britanniche",
    "VI":"Isole Vergini, U.S.",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis e Futuna",
    "WS":"Samoa",
    "YE":"Yemen",
    "ZA":"Sud Africa",
    "ZM":"Zambia",
    "ZW":"Zimbabwe"
  },
  "pt":{
    "AW":"Aruba",
    "AF":"Afeganistão",
    "AO":"Angola",
    "AI":"Anguilla",
    "AX":"Ilhas Åland",
    "AL":"Albânia",
    "AD":"Andorra",
    "AE":"Emirados Árabes Unidos",
    "AR":"Argentina",
    "AM":"Arménia",
    "AS":"Samoa Americana",
    "AQ":"Antárctida",
    "TF":"Territórios Franceses do Sul",
    "AG":"Antígua e Barbuda",
    "AU":"Austrália",
    "AT":"Áustria",
    "AZ":"Azerbaijão",
    "BI":"Burundi",
    "BE":"Bélgica",
    "BJ":"Benim",
    "BQ":"Bonaire, Santo Eustáquio e Saba",
    "BF":"Burkina Faso",
    "BD":"Bangladesh",
    "BG":"Bulgária",
    "BH":"Barein",
    "BS":"Bahamas",
    "BA":"Bósnia-Herzegóvina",
    "BL":"Saint Barthélemy",
    "BY":"Bielorússia",
    "BZ":"Belize",
    "BM":"Bermuda",
    "BO":"Bolívia",
    "BR":"Brasil",
    "BB":"Barbados",
    "BN":"Brunei",
    "BT":"Butão",
    "BV":"Ilha Bouvet",
    "BW":"Botsuana",
    "CF":"República Centro-Africana",
    "CA":"Canadá",
    "CC":"Ilhas Cocos",
    "CH":"Suíça",
    "CL":"Chile",
    "CN":"China",
    "CI":"Costa do Marfim",
    "CM":"Camarões",
    "CD":"Congo, República Democrática do",
    "CG":"Congo",
    "CK":"Ilhas Cook",
    "CO":"Colômbia",
    "KM":"Comoros",
    "CV":"Cabo Verde",
    "CR":"Costa Rica",
    "CU":"Cuba",
    "CW":"Curação",
    "CX":"Ilha Natal",
    "KY":"Ilhas Caimão",
    "CY":"Chipre",
    "CZ":"Czechia",
    "DE":"Alemanha",
    "DJ":"Djibouti",
    "DM":"Dominica",
    "DK":"Dinamarca",
    "DO":"República Dominicana",
    "DZ":"Argélia",
    "EC":"Equador",
    "EG":"Egipto",
    "ER":"Eritreia",
    "EH":"Sahara Ocidental",
    "ES":"Espanha",
    "EE":"Estónia",
    "ET":"Etiópia",
    "FI":"Finlândia",
    "FJ":"Fiji",
    "FK":"Ilhas Falkland (Malvinas)",
    "FR":"França",
    "FO":"Ilhas Feroé",
    "FM":"Micronesia, Estados Federados da",
    "GA":"Gabão",
    "GB":"Reino Unido",
    "GE":"Geórgia",
    "GG":"Guernsey",
    "GH":"Gana",
    "GI":"Gibraltar",
    "GN":"Guiné",
    "GP":"Guadalupe",
    "GM":"Gâmbia",
    "GW":"Guiné-Bissáu",
    "GQ":"Guiné Equatorial",
    "GR":"Grécia",
    "GD":"Granada",
    "GL":"Gronelândia",
    "GT":"Guatemala",
    "GF":"Guiana Francesa",
    "GU":"Guam",
    "GY":"Guiana",
    "HK":"Hong Kong",
    "HM":"Ilha Heard e Ilhas McDonald",
    "HN":"Honduras",
    "HR":"Croácia",
    "HT":"Haiti",
    "HU":"Hungria",
    "ID":"Indonésia",
    "IM":"Ilha de Man",
    "IN":"Índia",
    "IO":"Território Britânico do Oceano Índico",
    "IE":"Irlanda",
    "IR":"Irão, República Islâmica do",
    "IQ":"Iraque",
    "IS":"Islândia",
    "IL":"Israel",
    "IT":"Itália",
    "JM":"Jamaica",
    "JE":"Jersey",
    "JO":"Jordânia",
    "JP":"Japão",
    "KZ":"Cazaquistão",
    "KE":"Quénia",
    "KG":"Quirgistão",
    "KH":"Cambodja",
    "KI":"Kiribati",
    "KN":"Saint Kitts e Nevis",
    "KR":"Coreia, República da",
    "KW":"Kuwait",
    "LA":"República Democrática Popular do Laos",
    "LB":"Líbano",
    "LR":"Libéria",
    "LY":"Líbia",
    "LC":"Santa Lúcia",
    "LI":"Liechtenstein",
    "LK":"Sri Lanka",
    "LS":"Lesoto",
    "LT":"Lituânia",
    "LU":"Luxemburgo",
    "LV":"Letónia",
    "MO":"Macau",
    "MF":"São Martin (Território Francês)",
    "MA":"Marrocos",
    "MC":"Mónaco",
    "MD":"Moldávia",
    "MG":"Madagáscar",
    "MV":"Maldivas",
    "MX":"México",
    "MH":"Ilhas Marshall",
    "MK":"North Macedonia",
    "ML":"Mali",
    "MT":"Malta",
    "MM":"Myanmar",
    "ME":"Montenegro",
    "MN":"Mongólia",
    "MP":"Ilhas Marianas do Norte",
    "MZ":"Moçambique",
    "MR":"Mauritânia",
    "MS":"Montserrat",
    "MQ":"Martinica",
    "MU":"Maurícias",
    "MW":"Malawi",
    "MY":"Malásia",
    "YT":"Mayotte",
    "NA":"Namíbia",
    "NC":"Nova Caledónia",
    "NE":"Níger",
    "NF":"Ilha Norfolk",
    "NG":"Nigéria",
    "NI":"Nicarágua",
    "NU":"Niue",
    "NL":"Países Baixos",
    "NO":"Noruega",
    "NP":"Nepal",
    "NR":"Nauru",
    "NZ":"Nova Zelândia",
    "OM":"Oman",
    "PK":"Paquistão",
    "PA":"Panamá",
    "PN":"Pitcairn",
    "PE":"Peru",
    "PH":"Filipinas",
    "PW":"Palau",
    "PG":"Papua Nova Guiné",
    "PL":"Polónia",
    "PR":"Porto Rico",
    "KP":"Coreia, República Popular Democrática de ",
    "PT":"Portugal",
    "PY":"Paraguai",
    "PS":"Palestina, Autoridade da",
    "PF":"Polinésia Francesa",
    "QA":"Quatar",
    "RE":"Ilha Reunião",
    "RO":"Roménia",
    "RU":"Federação Russa",
    "RW":"Ruanda",
    "SA":"Arábia Saudita",
    "SD":"Sudão",
    "SN":"Senegal",
    "SG":"Singapura",
    "GS":"Geórgia do Sul e Ilhas Sandwich do Sul",
    "SH":"Santa Helema, Ascenção e Tristão da Cunha",
    "SJ":"Svalbard e Jan Mayen",
    "SB":"Ilhas Salomão",
    "SL":"Serra Leoa",
    "SV":"El Salvador",
    "SM":"San Marino",
    "SO":"Somália",
    "PM":"Saint Pierre e Miquelon",
    "RS":"Sérvia",
    "SS":"República do Sudão",
    "ST":"São Tomé e Príncipe",
    "SR":"Suriname",
    "SK":"Eslováquia",
    "SI":"Eslovénia",
    "SE":"Suécia",
    "SZ":"Eswatini",
    "SX":"São Martinho (Países Baixos)",
    "SC":"Seychelles",
    "SY":"República Árabe Síria",
    "TC":"Ilhas Turks e Caicos",
    "TD":"Chade",
    "TG":"Togo",
    "TH":"Tailândia",
    "TJ":"Tadjaquistão",
    "TK":"Tokelau",
    "TM":"Turcomenistão",
    "TL":"Timor-Leste",
    "TO":"Tonga",
    "TT":"Trinidade e Tobago",
    "TN":"Tunísia",
    "TR":"Turquia",
    "TV":"Tuvalu",
    "TW":"Taiwan",
    "TZ":"Tanzania",
    "UG":"Uganda",
    "UA":"Ucrânia",
    "UM":"Ilhas Menores Exteriores dos Estados Unidos",
    "UY":"Uruguai",
    "US":"Estados Unidos",
    "UZ":"Uzbequistão",
    "VA":"Santa Sé (Estado Cidade do Vaticano)",
    "VC":"São Vicente e Grenadinas",
    "VE":"Venezuela",
    "VG":"Ilhas Virgens, Britânicas",
    "VI":"Ilhas Virgens, Estados Unidos",
    "VN":"Vietnam",
    "VU":"Vanuatu",
    "WF":"Wallis e Futuna",
    "WS":"Samoa",
    "YE":"Yémen",
    "ZA":"África do Sul",
    "ZM":"Zâmbia",
    "ZW":"Zimbabwe"
  },
  "ru":{
    "AW":"Аруба",
    "AF":"Афганистан",
    "AO":"Ангола",
    "AI":"Ангвилла",
    "AX":"Аландские острова",
    "AL":"Албания",
    "AD":"Андорра",
    "AE":"Объединённые Арабские Эмираты",
    "AR":"Аргентина",
    "AM":"Армения",
    "AS":"Американские Самоа",
    "AQ":"Антарктика",
    "TF":"Французские южные территории",
    "AG":"Антигуа и Барбуда",
    "AU":"Австралия",
    "AT":"Австрия",
    "AZ":"Азербайджан",
    "BI":"Бурунди",
    "BE":"Бельгия",
    "BJ":"Бенин",
    "BQ":"Бонайре, Синт-Эстатиус и Саба",
    "BF":"Буркина-Фасо",
    "BD":"Бангладеш",
    "BG":"Болгария",
    "BH":"Бахрейн",
    "BS":"Багамы",
    "BA":"Босния и Герцеговина",
    "BL":"Сен-Бартельми",
    "BY":"Беларусь",
    "BZ":"Белиз",
    "BM":"Бермуды",
    "BO":"Боливия",
    "BR":"Бразилия",
    "BB":"Барбадос",
    "BN":"Бруней Даруссалам",
    "BT":"Бутан",
    "BV":"Остров Буве",
    "BW":"Ботсвана",
    "CF":"Центрально-африканская республика",
    "CA":"Канада",
    "CC":"Кокосовые острова ",
    "CH":"Швейцария",
    "CL":"Чили",
    "CN":"Китай",
    "CI":"Кот-д'Ивуар",
    "CM":"Камерун",
    "CD":"Демократическая Республика Конго",
    "CG":"Конго",
    "CK":"Острова Кука",
    "CO":"Колумбия",
    "KM":"Коморские острова",
    "CV":"Cabo Verde",
    "CR":"Коста-Рика",
    "CU":"Куба",
    "CW":"Кюрасао",
    "CX":"Остров Рождества",
    "KY":"Каймановы острова",
    "CY":"Кипр",
    "CZ":"Czechia",
    "DE":"Германия",
    "DJ":"Джибути",
    "DM":"Доминика",
    "DK":"Дания",
    "DO":"Доминиканская республика",
    "DZ":"Алжир",
    "EC":"Эквадор",
    "EG":"Египет",
    "ER":"Эритрея",
    "EH":"Западная Сахара",
    "ES":"Испания",
    "EE":"Эстония",
    "ET":"Эфиопия",
    "FI":"Финляндия",
    "FJ":"Фиджи",
    "FK":"Фолклендские (Мальвинские) острова",
    "FR":"Франция",
    "FO":"Фарерские острова",
    "FM":"Федеративные Штаты Микронезии",
    "GA":"Габон",
    "GB":"Соединённое Королевство",
    "GE":"Грузия",
    "GG":"Гернси",
    "GH":"Гана",
    "GI":"Гибралтар",
    "GN":"Гвинея",
    "GP":"Гваделупа",
    "GM":"Гамбия",
    "GW":"Гвинея-Бисау",
    "GQ":"Экваториальная Гвинея",
    "GR":"Греция",
    "GD":"Гренада",
    "GL":"Гренландия",
    "GT":"Гватемала",
    "GF":"Французская Гвиана",
    "GU":"Гуам",
    "GY":"Гайана",
    "HK":"Гонконг",
    "HM":"Остров Херд и острова МакДональд",
    "HN":"Гондурас",
    "HR":"Хорватия",
    "HT":"Гаити",
    "HU":"Венгрия",
    "ID":"Индонезия",
    "IM":"Остров Мэн",
    "IN":"Индия",
    "IO":"Британская территория Индийского океана",
    "IE":"Ирландия",
    "IR":"Иран",
    "IQ":"Ирак",
    "IS":"Исландия",
    "IL":"Израиль",
    "IT":"Италия",
    "JM":"Ямайка",
    "JE":"Джерси",
    "JO":"Иордания",
    "JP":"Япония",
    "KZ":"Казахстан",
    "KE":"Кения",
    "KG":"Кыргызстан",
    "KH":"Камбоджа",
    "KI":"Кирибати",
    "KN":"Сент-Китс и Невис",
    "KR":"Республика Корея",
    "KW":"Кувейт",
    "LA":"Лаосская Народно-Демократическая Республика",
    "LB":"Ливан",
    "LR":"Либерия",
    "LY":"Ливия",
    "LC":"Сент-Люсия",
    "LI":"Лихтенштейн",
    "LK":"Шри-Ланка",
    "LS":"Лесото",
    "LT":"Литва",
    "LU":"Люксембург",
    "LV":"Латвия",
    "MO":"Аомынь",
    "MF":"Сен-Мартен (Франция)",
    "MA":"Марокко",
    "MC":"Монако",
    "MD":"Молдавия",
    "MG":"Мадагаскар",
    "MV":"Мальдивы",
    "MX":"Мексика",
    "MH":"Маршалловы острова",
    "MK":"North Macedonia",
    "ML":"Мали",
    "MT":"Мальта",
    "MM":"Мьянма",
    "ME":"Черногория",
    "MN":"Монголия",
    "MP":"Острова северной Марианы",
    "MZ":"Мозамбик",
    "MR":"Мавритания",
    "MS":"Монсеррат",
    "MQ":"Мартиника",
    "MU":"Маврикий",
    "MW":"Малави",
    "MY":"Малайзия",
    "YT":"Майот",
    "NA":"Намибия",
    "NC":"Новая Каледония",
    "NE":"Нигер",
    "NF":"Остров Норфолк",
    "NG":"Нигерия",
    "NI":"Никарагуа",
    "NU":"Ниуэ",
    "NL":"Нидерланды",
    "NO":"Норвегия",
    "NP":"Непал",
    "NR":"Науру",
    "NZ":"Новая Зеландия",
    "OM":"Оман",
    "PK":"Пакистан",
    "PA":"Панама",
    "PN":"Питкэрн",
    "PE":"Перу",
    "PH":"Филиппины",
    "PW":"Палау",
    "PG":"Папуа — Новая Гвинея",
    "PL":"Польша",
    "PR":"Пуэрто-Рико",
    "KP":"Корейская Народно-Демократическая Республика",
    "PT":"Португалия",
    "PY":"Парагвай",
    "PS":"Палестина",
    "PF":"Французская Полинезия",
    "QA":"Катар",
    "RE":"Реюньон",
    "RO":"Румыния",
    "RU":"Российская Федерация",
    "RW":"Руанда",
    "SA":"Саудовская Аравия",
    "SD":"Судан",
    "SN":"Сенегал",
    "SG":"Сингапур",
    "GS":"Южная Джорджия и Южные Сандвичевы острова ",
    "SH":"Остров Святой Елены, Остров Вознесения и Тристан-да-Кунья",
    "SJ":"Шпицберген и Ян-Майен",
    "SB":"Соломоновы Острова",
    "SL":"Сьерра-Леоне",
    "SV":"Сальвадор",
    "SM":"Сан-Марино",
    "SO":"Сомали",
    "PM":"Сен-Пьер и Микелон",
    "RS":"Сербия",
    "SS":"Южный Судан",
    "ST":"Сан-Томе и Принсипи",
    "SR":"Суринам",
    "SK":"Словакия",
    "SI":"Словения",
    "SE":"Швеция",
    "SZ":"Eswatini",
    "SX":"Синт-Мартен (голландская часть)",
    "SC":"Сейшельские Острова",
    "SY":"Сирийская Арабская Республика",
    "TC":"Острова Туркс и Каикос",
    "TD":"Чад",
    "TG":"Того",
    "TH":"Таиланд",
    "TJ":"Таджикистан",
    "TK":"Токелау",
    "TM":"Туркменистан",
    "TL":"Восточный Тимор",
    "TO":"Тонга",
    "TT":"Тринидад и Тобаго",
    "TN":"Тунис",
    "TR":"Турция",
    "TV":"Тувалу",
    "TW":"Тайвань",
    "TZ":"Танзания",
    "UG":"Уганда",
    "UA":"Украина",
    "UM":"Соединенные штаты Малых  Удаленных островов",
    "UY":"Уругвай",
    "US":"Соединённые штаты",
    "UZ":"Узбекистан",
    "VA":"Государство-город Ватикан",
    "VC":"Сент-Винсент и Гренадины",
    "VE":"Венесуэла",
    "VG":"Виргинские острова (Британия)",
    "VI":"Виргинские острова (США)",
    "VN":"Vietnam",
    "VU":"Вануату",
    "WF":"Уоллес и Футана",
    "WS":"Самоа",
    "YE":"Йемен",
    "ZA":"Южная Африка",
    "ZM":"Замбия",
    "ZW":"Зимбабве"
  },
  "is":{
    "AW":"Arúba",
    "AF":"Afganistan",
    "AO":"Angóla",
    "AI":"Angvíla",
    "AX":"Álandseyjar",
    "AL":"Albanía",
    "AD":"Andorra",
    "AE":"Sameinuðu arabísku furstadæmin",
    "AR":"Argentína",
    "AM":"Armenía",
    "AS":"Bandarísku Samóaeyjar",
    "AQ":"Suðurskautslandið",
    "TF":"Frönsku suðurhafshéruðin",
    "AG":"Antigúa og Barbúda",
    "AU":"Ástralía",
    "AT":"Austurríki",
    "AZ":"Aserbaídsjan",
    "BI":"Búrúndí",
    "BE":"Belgía",
    "BJ":"Benín",
    "BQ":"Bonaire, Sankti Eustatius og Saba",
    "BF":"Búrkína Fasó",
    "BD":"Bangladess",
    "BG":"Búlgaría",
    "BH":"Barein",
    "BS":"Bahamaeyjar",
    "BA":"Bosnía og Herzegóvína",
    "BL":"Sankti Bartelemí",
    "BY":"Hvítarússland",
    "BZ":"Belís",
    "BM":"Bermúda",
    "BO":"Bólivía",
    "BR":"Brasilía",
    "BB":"Barbados",
    "BN":"Brúnei Darussalam",
    "BT":"Bútan",
    "BV":"Bouvet eyja",
    "BW":"Botsvana",
    "CF":"Miðafríkulýðveldið",
    "CA":"Kanada",
    "CC":"Kókoseyjar (Keeling-eyjar)",
    "CH":"Sviss",
    "CL":"Síle",
    "CN":"Kína",
    "CI":"Fílabeinsströnd",
    "CM":"Kamerún",
    "CD":"Kongó, sambandslýðveldið",
    "CG":"Kongó",
    "CK":"Cook-eyjar",
    "CO":"Kólumbía",
    "KM":"Kómoreyjar",
    "CV":"Cabo Verde",
    "CR":"Kosta Ríka",
    "CU":"Kúba",
    "CW":"Curaçao",
    "CX":"Jólaeyja",
    "KY":"Cayman-eyjar",
    "CY":"Kýpur",
    "CZ":"Czechia",
    "DE":"Þýskaland",
    "DJ":"Djíbútí",
    "DM":"Dóminíka",
    "DK":"Danmörk",
    "DO":"Lýðveldið Dóminíka",
    "DZ":"Alsír",
    "EC":"Ekvador",
    "EG":"Egyptaland",
    "ER":"Erítrea",
    "EH":"Vestur-Sahara",
    "ES":"Spánn",
    "EE":"Eistland",
    "ET":"Eþíópía",
    "FI":"Finnland",
    "FJ":"Fídjieyjar",
    "FK":"Falklandseyjar (Malvinaeyjar)",
    "FR":"Frakkland",
    "FO":"Færeyjar",
    "FM":"Míkrónesía, Sambandsríki",
    "GA":"Gabon",
    "GB":"Breska samveldið",
    "GE":"Georgía",
    "GG":"Guernsey",
    "GH":"Gana",
    "GI":"Gíbraltar",
    "GN":"Gínea",
    "GP":"Gvadalúp",
    "GM":"Gambía",
    "GW":"Gínea-Bissá",
    "GQ":"Miðbaugs-Gínea",
    "GR":"Grikkland",
    "GD":"Grenada",
    "GL":"Grænland",
    "GT":"Gvatemala",
    "GF":"Franska Gvæjana",
    "GU":"Gvam",
    "GY":"Gvæjana",
    "HK":"Hong Kong",
    "HM":"Heard-eyja og McDonald-eyjur",
    "HN":"Hondúras",
    "HR":"Króatía",
    "HT":"Haítí",
    "HU":"Ungverjaland",
    "ID":"Indónesía",
    "IM":"Eyjan Mön",
    "IN":"Indland",
    "IO":"Bresku Indlandshafseyjar",
    "IE":"Írland",
    "IR":"Íran, íslamska lýðveldið",
    "IQ":"Írak",
    "IS":"Ísland",
    "IL":"Ísrael",
    "IT":"Ítalía",
    "JM":"Jamaíka",
    "JE":"Jersey",
    "JO":"Jórdanía",
    "JP":"Japan",
    "KZ":"Kasakstan",
    "KE":"Kenía",
    "KG":"Kirgisistan",
    "KH":"Kambódía",
    "KI":"Kíribatí",
    "KN":"Sankti Kitts og Neviseyjur",
    "KR":"Lýðveldið Suður-Kórea",
    "KW":"Kúveit",
    "LA":"Alþýðulýðveldið Laó",
    "LB":"Líbanon",
    "LR":"Líbería",
    "LY":"Líbýa",
    "LC":"Sankti Lúsía",
    "LI":"Liechtenstein",
    "LK":"Srí Lanka",
    "LS":"Lesótó",
    "LT":"Litháen",
    "LU":"Lúxemborg",
    "LV":"Lettland",
    "MO":"Makaó",
    "MF":"Sankti Martin (franski hluti)",
    "MA":"Marokkó",
    "MC":"Mónakó",
    "MD":"Moldavía",
    "MG":"Madagaskar",
    "MV":"Maldíveyjar",
    "MX":"Mexíkó",
    "MH":"Marshalleyjar",
    "MK":"North Macedonia",
    "ML":"Malí",
    "MT":"Malta",
    "MM":"Mjanmar",
    "ME":"Svartfjallaland",
    "MN":"Mongólía",
    "MP":"Norður-Maríanaeyjar",
    "MZ":"Mósambík",
    "MR":"Máritanía",
    "MS":"Montserrat",
    "MQ":"Martiník",
    "MU":"Máritus",
    "MW":"Malaví",
    "MY":"Malasía",
    "YT":"Mayott",
    "NA":"Namibía",
    "NC":"Nýja Kaledónía",
    "NE":"Níger",
    "NF":"Norfolkeyja",
    "NG":"Nígería",
    "NI":"Níkaragva",
    "NU":"Niue",
    "NL":"Holland",
    "NO":"Noregur",
    "NP":"Nepal",
    "NR":"Nárú",
    "NZ":"Nýja Sjáland",
    "OM":"Óman",
    "PK":"Pakistan",
    "PA":"Panama",
    "PN":"Pitkairn-eyja",
    "PE":"Perú",
    "PH":"Filippseyjar",
    "PW":"Palá",
    "PG":"Papúa Nýja-Gínea",
    "PL":"Pólland",
    "PR":"Puerto Ríko",
    "KP":"Norður-Kórea, sambandsalþýðulýðveldið",
    "PT":"Portúgal",
    "PY":"Paragvæ",
    "PS":"Palestína",
    "PF":"Franska Pólýnesía",
    "QA":"Katar",
    "RE":"Réunion",
    "RO":"Rúmenía",
    "RU":"Rússneska sambandið",
    "RW":"Rúanda",
    "SA":"Sádí-Arabía",
    "SD":"Súdan",
    "SN":"Senegal",
    "SG":"Singapúr",
    "GS":"Suður-Georgía og Suður-Sandwich eyjar",
    "SH":"Sankti Helena, Ascension og Tristan da Cunha",
    "SJ":"Svalbarði og Jan Mayen",
    "SB":"Salómonseyjar",
    "SL":"Síerra Leóne",
    "SV":"El Salvador",
    "SM":"San Marínó",
    "SO":"Sómalía",
    "PM":"Sankti Pierre og Miquelon",
    "RS":"Serbía",
    "SS":"Suður-súdan",
    "ST":"Saó Tóme og Prinsípe",
    "SR":"Súrínam",
    "SK":"Slóvakía",
    "SI":"Slóvenía",
    "SE":"Svíþjóð",
    "SZ":"Eswatini",
    "SX":"Sankti Maarten (hollenski hluti)",
    "SC":"Seychelles-eyjar",
    "SY":"Sýrlenska arabalýðveldið",
    "TC":"Turks og Kaikós eyjar",
    "TD":"Tsjad",
    "TG":"Tógó",
    "TH":"Tæland",
    "TJ":"Tadsíkistan",
    "TK":"Tókelá",
    "TM":"Túrkmenistan",
    "TL":"Tímor-Leste",
    "TO":"Tonga",
    "TT":"Trínidad og Tóbagó",
    "TN":"Túnis",
    "TR":"Tyrkland",
    "TV":"Túvalú",
    "TW":"Tævan",
    "TZ":"Tansanía",
    "UG":"Úganda",
    "UA":"Úkraína",
    "UM":"Ytri-smáeyjar Bandaríkjanna",
    "UY":"Úrúgvæ",
    "US":"Bandaríkin",
    "UZ":"Úsbekistan",
    "VA":"Borgríkið Vatíkanið",
    "VC":"Sankti Vincent og Grenadineeyjar",
    "VE":"Venesúela",
    "VG":"Jómfrúareyjar, bresku",
    "VI":"Jómfrúareyjar, BNA",
    "VN":"Vietnam",
    "VU":"Vanuatú",
    "WF":"Wallis- og Fútúnaeyjar",
    "WS":"Samóa",
    "YE":"Jemen",
    "ZA":"Suður Afríka",
    "ZM":"Sambía",
    "ZW":"Simbabve"
  }
}

function localizeCountries (country) {
  const countryMap = Object.keys(countries.en).reduce((map, code) => {
    map[countries.en[code]] = countries[country][code]

    return map
  }, {})

  fs.writeFile(`${country}.json`, JSON.stringify(countryMap), err => {
    if (err) return console.log(err)
    console.log(`countryMap for ${country} > ${country}.json`)
  })
}

for (const country of Object.keys(countries)) {
  localizeCountries(country)
}
