#!/usr/bin/env bash

# Opens up the apps I use for work

# Ensure the Python env is running,
# so we can use apps like watson
source ~/venv/bin/activate

cd ~/projects/pa/web && pnpm run start
chromium https://localhost:5173 & disown

