#!/usr/bin/env bash

# Opens up the apps I use for work

open -a "Google Chrome.app" \
  https://localhost:5173 \

open -a "JetBrains Space.app"
open -a "Figma.app"

cd ~/projects/pa/ && code .
open -a "Spotify.app"

