#!/bin/bash

# NB: You need to run this as `. startwork` instead of just `startwork`,
# so the `cd` command will run in your current shell and not in the script's subshell

cd ~/projects/pa/web || { echo "Failed to change directory"; exit 1; }

source ~/venv/bin/activate && watson start pa
