#!/usr/bin/env bash

# Updates hourly rate in invox config file

set -u
set -e
set -o pipefail

config="/Users/alacritas/.config/invox/.invoxrc"

converted=$(cash 50 USD GBP 2>&1 >/dev/null)
readarray -t lines <<<"$converted"

message="${lines[1]}"
echo "$message"

value=$(echo "$message" | grep -oE '[0-9]+([.][0-9]+)?')

rate_string=$(ggrep -P 'hourly_rate=[A-Za-z0-9]*' "$config")
new_rate_string=$(echo "$rate_string" | gsed -E "s/[0-9]+([.][0-9]+)?/${value}/g")

echo $new_rate_string

gsed -i "s/${rate_string}/${new_rate_string}/" "$config"

bat "$config"

exit
