#!/bin/bash

# Update working branch by pulling base branch and merging it into working branch.

set -x

if [ -z "$1" ]; then
  echo "Usage: update-working-branch <base_branch>"
  exit 1
fi

base_branch=$1
working_branch=$(git rev-parse --abbrev-ref HEAD)

if ! git diff-index --quiet HEAD --; then
  git stash --include-untracked
  has_stash=true
fi

git checkout $base_branch && git pull && git checkout $working_branch && git pull

if [ "$has_stash" = true ]; then
  git stash pop
fi

git merge $base_branch
