#!/bin/bash

# Update working branch by pulling base branch and merging it into working branch.

set -x

if [ -z "$1" ]; then
  echo "Usage: update-working-branch <base_branch>"
  exit 1
fi

base_branch=$1
working_branch=$(git rev-parse --abbrev-ref HEAD)

git stash --include-untracked
git checkout $base_branch && git pull && git checkout $working_branch && git pull
git stash pop
git merge $base_branch
