#!/bin/bash

# Update working branch by pulling base branch and merging it into working branch.

set -x

if [ -z "$1" ]; then
  echo "Usage: update-working-branch <base_branch>"
  exit 1
fi

base_branch=$1

if ! git diff-index --quiet HEAD --; then
  git stash --include-untracked
  has_stash=true
fi

if [ "$(git rev-parse --abbrev-ref HEAD)" = "$base_branch" ]; then
  echo "Already on $base_branch — use 'git pull' instead."
  exit 1
fi

git fetch origin $base_branch:$base_branch && git pull

if [ "$has_stash" = true ]; then
  git stash pop
fi

git merge origin/$base_branch
